"""create college notices table

Revision ID: 13958b595b51
Revises: 2a9b24964e39
Create Date: 2026-10-01 17:39:34.993800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '13958b595b51'
down_revision: Union[str, Sequence[str], None] = '2a9b24964e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_notices_category'), 'college_notices', ['category'], unique=False)
    op.create_index(op.f('ix_college_notices_id'), 'college_notices', ['id'], unique=False)
    op.create_index(op.f('ix_college_notices_priority'), 'college_notices', ['priority'], unique=False)
    op.create_index(op.f('ix_college_notices_published_at'), 'college_notices', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_college_notices_published_at'), table_name='college_notices')
    op.drop_index(op.f('ix_college_notices_priority'), table_name='college_notices')
    op.drop_index(op.f('ix_college_notices_id'), table_name='college_notices')
    op.drop_index(op.f('ix_college_notices_category'), table_name='college_notices')
    op.drop_table('college_notices')
    # ### end Alembic commands ###
