"""update student model

Revision ID: 1957146d2369
Revises: 37e42729d772
Create Date: 2026-09-25 09:43:15.059276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '1957146d2369'
down_revision: Union[str, Sequence[str], None] = '37e42729d772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
