"""create student documents table

Revision ID: 2a9b24964e39
Revises: 3bd8f8636443
Create Date: 2026-10-01 16:38:50.578127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2a9b24964e39'
down_revision: Union[str, Sequence[str], None] = '3bd8f8636443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_document_type'), 'student_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    op.create_index(op.f('ix_student_documents_status'), 'student_documents', ['status'], unique=False)
    op.create_index(op.f('ix_student_documents_student_id'), 'student_documents', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_documents_student_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_status'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_document_type'), table_name='student_documents')
    op.drop_table('student_documents')
    # ### end Alembic commands ###
