"""update student model

Revision ID: 37e42729d772
Revises: c34ffba64483
Create Date: 2026-09-25 09:42:20.716925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '37e42729d772'
down_revision: Union[str, Sequence[str], None] = 'c34ffba64483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('admission_year', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('students_user_id_key'), 'students', type_='unique')
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_foreign_key(None, 'students', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('students', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.create_unique_constraint(op.f('students_user_id_key'), 'students', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'admission_year')
    op.drop_column('students', 'department_id')
    # ### end Alembic commands ###
