"""create faculty table

Revision ID: 884e2e6f483c
Revises: ba4bd0d8453e
Create Date: 2026-09-28 12:59:35.355553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '884e2e6f483c'
down_revision: Union[str, Sequence[str], None] = 'ba4bd0d8453e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('joining_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_department_id'), 'faculty', ['department_id'], unique=False)
    op.create_index(op.f('ix_faculty_employee_id'), 'faculty', ['employee_id'], unique=True)
    op.create_index(op.f('ix_faculty_id'), 'faculty', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_user_id'), 'faculty', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_user_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_employee_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_department_id'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
