"""add cloudinary public id to documents

Revision ID: 9ac80b7a787e
Revises: 5a19711ab3ac
Create Date: 2026-10-03 14:03:59.603826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9ac80b7a787e'
down_revision: Union[str, Sequence[str], None] = '5a19711ab3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_documents', sa.Column('cloudinary_public_id', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_student_documents_cloudinary_public_id'), 'student_documents', ['cloudinary_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_documents_cloudinary_public_id'), table_name='student_documents')
    op.drop_column('student_documents', 'cloudinary_public_id')
    # ### end Alembic commands ###
