"""create exams table

Revision ID: c08e45a86953
Revises: 9679bf2a6cb4
Create Date: 2026-10-01 14:44:17.433047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'c08e45a86953'
down_revision: Union[str, Sequence[str], None] = '9679bf2a6cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=False),
    sa.Column('exam_type', sa.String(length=30), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_exam_date'), 'exams', ['exam_date'], unique=False)
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_index(op.f('ix_exams_semester'), 'exams', ['semester'], unique=False)
    op.create_index(op.f('ix_exams_subject_code'), 'exams', ['subject_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_subject_code'), table_name='exams')
    op.drop_index(op.f('ix_exams_semester'), table_name='exams')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_date'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
