"""create no dues tables

Revision ID: d4133b446958
Revises: 1957146d2369
Create Date: 2026-09-25 10:37:58.882852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd4133b446958'
down_revision: Union[str, Sequence[str], None] = '1957146d2369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_dues_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', name='noduesstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_no_dues_requests_id'), 'no_dues_requests', ['id'], unique=False)
    op.create_index(op.f('ix_no_dues_requests_student_id'), 'no_dues_requests', ['student_id'], unique=False)
    op.create_table('no_dues_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_dues_request_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('LIBRARY', 'ACCOUNTS', 'HOSTEL', 'LAB', 'DEPARTMENT', name='noduesdepartment'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', name='noduesstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['no_dues_request_id'], ['no_dues_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_no_dues_approvals_id'), 'no_dues_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_no_dues_approvals_no_dues_request_id'), 'no_dues_approvals', ['no_dues_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_no_dues_approvals_no_dues_request_id'), table_name='no_dues_approvals')
    op.drop_index(op.f('ix_no_dues_approvals_id'), table_name='no_dues_approvals')
    op.drop_table('no_dues_approvals')
    op.drop_index(op.f('ix_no_dues_requests_student_id'), table_name='no_dues_requests')
    op.drop_index(op.f('ix_no_dues_requests_id'), table_name='no_dues_requests')
    op.drop_table('no_dues_requests')
    # ### end Alembic commands ###
