"""create out pass tables

Revision ID: d903676b84f0
Revises: d4133b446958
Create Date: 2026-09-25 20:56:00.923346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd903676b84f0'
down_revision: Union[str, Sequence[str], None] = 'd4133b446958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('out_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('emergency_contact', sa.String(length=20), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('expected_return_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'USED', 'EXPIRED', 'CANCELLED', name='outpassstatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('qr_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_out_passes_id'), 'out_passes', ['id'], unique=False)
    op.create_index(op.f('ix_out_passes_qr_token'), 'out_passes', ['qr_token'], unique=True)
    op.create_index(op.f('ix_out_passes_status'), 'out_passes', ['status'], unique=False)
    op.create_index(op.f('ix_out_passes_student_id'), 'out_passes', ['student_id'], unique=False)
    op.create_table('out_pass_scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('out_pass_id', sa.Integer(), nullable=False),
    sa.Column('scanned_by', sa.Integer(), nullable=True),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['out_pass_id'], ['out_passes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_out_pass_scan_logs_id'), 'out_pass_scan_logs', ['id'], unique=False)
    op.create_index(op.f('ix_out_pass_scan_logs_out_pass_id'), 'out_pass_scan_logs', ['out_pass_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_out_pass_scan_logs_out_pass_id'), table_name='out_pass_scan_logs')
    op.drop_index(op.f('ix_out_pass_scan_logs_id'), table_name='out_pass_scan_logs')
    op.drop_table('out_pass_scan_logs')
    op.drop_index(op.f('ix_out_passes_student_id'), table_name='out_passes')
    op.drop_index(op.f('ix_out_passes_status'), table_name='out_passes')
    op.drop_index(op.f('ix_out_passes_qr_token'), table_name='out_passes')
    op.drop_index(op.f('ix_out_passes_id'), table_name='out_passes')
    op.drop_table('out_passes')
    # ### end Alembic commands ###
